# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Testing Pipeline

on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, edited, closed]
    branches: [main]

jobs:
  test-backend-cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: INSTALL PROJECT DEPENDENCIES
        run: npm ci

      - name: UNIT TEST (JEST)
        run: npm test

  test-backend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/src
    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: INSTALL PROJECT DEPENDENCIES
        run: npm ci

      - name: UNIT TEST (JEST)
        run: npm test

  test-frontend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: INSTALL PROJECT DEPENDENCIES
        run: npm ci

      - name: UNIT TEST (JEST)
        run: npm test
